//
//  SA_DiceExpressionStringConstants.m
//
//  Copyright 2016-2021 Said Achmiz.
//  See LICENSE and README.md for more info.

#import "SA_DiceExpressionStringConstants.h"

/***************************************************************/
#pragma mark String constants for retrieving string format rules
/***************************************************************/

NSString * const SA_DB_STRING_FORMAT_RULES_PLIST_NAME							=	@"SA_DB_StringFormatRules";

NSString * const SA_DB_VALID_CHARACTERS											=	@"SA_DB_VALID_CHARACTERS";
NSString * const SA_DB_VALID_NUMERAL_CHARACTERS									=	@"SA_DB_VALID_NUMERAL_CHARACTERS";
NSString * const SA_DB_VALID_OPERATOR_CHARACTERS									=	@"SA_DB_VALID_OPERATOR_CHARACTERS";
NSString * const SA_DB_VALID_ROLL_COMMAND_DELIMITER_CHARACTERS					=	@"SA_DB_VALID_ROLL_COMMAND_DELIMITER_CHARACTERS";
NSString * const SA_DB_VALID_ROLL_MODIFIER_DELIMITER_CHARACTERS					=	@"SA_DB_VALID_ROLL_MODIFIER_DELIMITER_CHARACTERS";

NSString * const SA_DB_CANONICAL_REPRESENTATIONS									=	@"SA_DB_CANONICAL_REPRESENTATIONS";
NSString * const SA_DB_CANONICAL_OPERATOR_REPRESENTATIONS						=	@"SA_DB_CANONICAL_OPERATOR_REPRESENTATIONS";
NSString * const SA_DB_CANONICAL_ROLL_COMMAND_DELIMITER_REPRESENTATIONS			=	@"SA_DB_CANONICAL_ROLL_COMMAND_DELIMITER_REPRESENTATIONS";
NSString * const SA_DB_CANONICAL_ROLL_MODIFIER_DELIMITER_REPRESENTATIONS			=	@"SA_DB_CANONICAL_ROLL_MODIFIER_DELIMITER_REPRESENTATIONS";
